main = ".open-next/worker.js"
name = "next-todo-app"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]
routes = [{ pattern = "tsutsutaku.com", custom_domain = true }]
[assets]
directory = ".open-next/assets"
binding = "ASSETS"
